name: Count Secret References

on: [push, pull_request]

jobs:
  count-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Count secret references
        id: count_secrets
        run: |
          count=$(grep -r -o '\${{ secrets.LIQUIBASE_COMMAND_PASSWORD }}' . | wc -l)
          echo "secret_count=$count" >> $GITHUB_ENV

      - name: Output secret count
        run: echo "The secret \${{ secrets.LIQUIBASE_COMMAND_PASSWORD }} appears ${{ env.secret_count }} times in the repository."
