name: Count Secret References in Merge

on:
  workflow_dispatch:
  pull_request:

jobs:
  count-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          
      - name: Set up Git identity
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create temporary branch for merge
        run: |
          git checkout -b temp-merge-branch
          git fetch origin ${{ github.head_ref }}
          git merge --no-commit --no-ff origin/${{ github.head_ref }}

      - name: Count secret references in the merged result
        id: count_secrets
        run: |
          # Contar las referencias en el resultado del merge
          count=$(grep -r -o 'secrets.LIQUIBASE_COMMAND_PASSWORD' . | wc -l)
          echo "secret_count=$count" >> $GITHUB_ENV

      - name: Output secret count
        run: |
          echo "The string 'secrets.LIQUIBASE_COMMAND_PASSWORD' appears ${{ env.secret_count }} times in the merged result."

      - name: Fail if more than one reference in the merged result
        if: ${{ env.secret_count }} -gt 1
        run: |
          echo "Error: The string 'secrets.LIQUIBASE_COMMAND_PASSWORD' is referenced more than once in the merged result."
          exit 1

      - name: Clean up
        run: |
          git checkout ${{ github.event.pull_request.base.ref }}
          git branch -D temp-merge-branch
