name: Count Secret References

on:
  workflow_dispatch:
  pull_request:

jobs:
  count-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Count secret references
        id: count_secrets
        run: |
          # Buscar la cadena exacta en el repositorio
          count=$(grep -r -o 'secrets.LIQUIBASE_COMMAND_PASSWORD' . | wc -l)
          echo "secret_count=$count" >> $GITHUB_ENV

      - name: Output secret count
        run: echo "The string 'secrets.LIQUIBASE_COMMAND_PASSWORD' appears ${{ env.secret_count }} times in the repository."

      - name: Fail if more than one reference
        if: ${{ env.secret_count }} -gt 1
        run: |
          echo "Error: The string 'secrets.LIQUIBASE_COMMAND_PASSWORD' is referenced more than once."
          exit 1
