name: Count Secret References

on:
  workflow_dispatch:
  pull_request:

jobs:
  count-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Count secret references in base branch
        id: count_base
        run: |
          base_count=$(grep -r -o 'secrets.LIQUIBASE_COMMAND_PASSWORD' . | wc -l)
          echo "base_secret_count=$base_count" >> $GITHUB_ENV

      - name: Checkout feature branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Count secret references in feature branch
        id: count_feature
        run: |
          feature_count=$(grep -r -o 'secrets.LIQUIBASE_COMMAND_PASSWORD' . | wc -l)
          echo "feature_secret_count=$feature_count" >> $GITHUB_ENV

      - name: Output secret counts
        run: |
          echo "Base branch secret count: ${{ env.base_secret_count }}"
          echo "Feature branch secret count: ${{ env.feature_secret_count }}"

      - name: Fail if more than one reference in either branch
        if: ${{ env.base_secret_count }} -gt 1 || ${{ env.feature_secret_count }} -gt 1
        run: |
          echo "Error: The string 'secrets.LIQUIBASE_COMMAND_PASSWORD' is referenced more than once in one of the branches."
          exit 1
